### ISSUE TITLE
nestJS 강의 완강

### ISSUE THREAD

**Issue by opehn** [dap-arm-ji/Daj-Server#2]
Due date : 3월 14일 목요일 12시 전까지

- [x] 3월 7일 : 8, 9강
- [x] 3월 8일 : 10, 11강 절반
- [x] 3월 9일 : 11강 절반, 12강
- [x] 3월 10일 : 13, 14강
- [x] 3월 11일 : 15강
- [x] 3월 12일 : 16강
- [x] 3월 13일 : 17, 18강

**Comment by hsju0202** [comment]
타이틀이 성함을 추가하는 것보다 오른쪽에 Assignees에 안나님 프로필을 추가하는게 깔끔할 것 같습니다!
