### ISSUE TITLE
GDB 스키마 설계 (가안)

### ISSUE THREAD

**Issue by opehn** [dap-arm-ji/Daj-Server#8]
- [x] 관계형 데이터베이스로 설계
- [x] Neo4j로 설계 마이그레이션(?)

**Comment by hsju0202** [comment]
## GDB Diagram 예시입니다!

RDB의 ERD와 다이어그램 그리는 방법이 다를 것 같아 찾아보았습니다.

issue 제목도 ERD 설계가 아니라 GDB schema 설계가 적절할 것 같습니다!

- 간단한 버전 (출처: [stackoverflow](https://stackoverflow.com/questions/45350724/neo4j-entity-relationship-diagram))
![Image](https://github.com/dap-arm-ji/Daj-Server/assets/57715601/f417d883-7871-4d7a-8109-5d3af3c42f66)
(movie, person은 노드의 유형이고, 화살표 사이의 DIRECTED, WROTE, PRODUDED 등은 노드간 가질 수 있는 관계입니다)

- 노드별 속성 포함한 버전 (출처: [neo4j docs](https://neo4j.com/blog/rdbms-vs-graph-data-modeling))
![Image](https://github.com/dap-arm-ji/Daj-Server/assets/57715601/d2e1d168-dcec-4487-a7b2-41dc688f3cb0)
